"""create panel table

Revision ID: 028e411b8ee4
Revises: cc028c2307c3
Create Date: 2021-09-13 11:35:47.254212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028e411b8ee4'
down_revision = 'cc028c2307c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_type', sa.Integer(), nullable=True),
    sa.Column('panel_lot', sa.String(length=25), nullable=True),
    sa.Column('panel_e_dat', sa.Date(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('run', 'lot_p6')
    op.drop_column('run', 'e_dat_p4')
    op.drop_column('run', 'e_dat_p5')
    op.drop_column('run', 'e_dat_p3')
    op.drop_column('run', 'lot_p1')
    op.drop_column('run', 'lot_p5')
    op.drop_column('run', 'lot_p2')
    op.drop_column('run', 'e_dat_p2')
    op.drop_column('run', 'lot_p4')
    op.drop_column('run', 'lot_p3')
    op.drop_column('run', 'e_dat_p6')
    op.drop_column('run', 'e_dat_p1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('e_dat_p1', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('e_dat_p6', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('lot_p3', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('lot_p4', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('e_dat_p2', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('lot_p2', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('lot_p5', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('lot_p1', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('e_dat_p3', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('e_dat_p5', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('e_dat_p4', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('lot_p6', sa.VARCHAR(), nullable=True))
    op.drop_table('panel')
    # ### end Alembic commands ###
