"""got rid of error table altogether

Revision ID: 3479d47f8e20
Revises: 
Create Date: 2021-09-02 15:04:03.296564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3479d47f8e20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('operator_1', sa.String(), nullable=False),
    sa.Column('operator_2', sa.String(), nullable=True),
    sa.Column('date_begin', sa.String(), nullable=False),
    sa.Column('date_end', sa.String(), nullable=True),
    sa.Column('final_dis', sa.String(), nullable=False),
    sa.Column('lot_p1', sa.String(), nullable=True),
    sa.Column('e_dat_p1', sa.String(), nullable=True),
    sa.Column('lot_p2', sa.String(), nullable=True),
    sa.Column('e_dat_p2', sa.String(), nullable=True),
    sa.Column('lot_p3', sa.String(), nullable=True),
    sa.Column('e_dat_p3', sa.String(), nullable=True),
    sa.Column('lot_p4', sa.String(), nullable=True),
    sa.Column('e_dat_p4', sa.String(), nullable=True),
    sa.Column('lot_p5', sa.String(), nullable=True),
    sa.Column('e_dat_p5', sa.String(), nullable=True),
    sa.Column('lot_p6', sa.String(), nullable=True),
    sa.Column('e_dat_p6', sa.String(), nullable=True),
    sa.Column('lot_nc', sa.String(), nullable=True),
    sa.Column('e_dat_nc', sa.String(), nullable=True),
    sa.Column('lot_vii', sa.String(), nullable=False),
    sa.Column('e_dat_vii', sa.String(), nullable=True),
    sa.Column('bsc_id', sa.String(), nullable=True),
    sa.Column('bsc_cdd', sa.String(length=7), nullable=True),
    sa.Column('pip_id', sa.String(), nullable=True),
    sa.Column('pip_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii1_id', sa.String(length=8), nullable=False),
    sa.Column('vii1_cdd', sa.String(length=7), nullable=False),
    sa.Column('vii2_id', sa.String(length=8), nullable=True),
    sa.Column('vii2_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii3_id', sa.String(length=8), nullable=True),
    sa.Column('vii3_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii4_id', sa.String(length=8), nullable=True),
    sa.Column('vii4_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii5_id', sa.String(length=8), nullable=True),
    sa.Column('vii5_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii6_id', sa.String(length=8), nullable=True),
    sa.Column('vii6_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii7_id', sa.String(length=8), nullable=True),
    sa.Column('vii7_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii8_id', sa.String(length=8), nullable=True),
    sa.Column('vii8_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii9_id', sa.String(length=8), nullable=True),
    sa.Column('vii9_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii10_id', sa.String(length=8), nullable=True),
    sa.Column('vii10_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii11_id', sa.String(length=8), nullable=True),
    sa.Column('vii11_cdd', sa.String(length=7), nullable=True),
    sa.Column('vii12_id', sa.String(length=8), nullable=True),
    sa.Column('vii12_cdd', sa.String(length=7), nullable=True),
    sa.Column('is_ie', sa.Boolean(), nullable=True),
    sa.Column('ie1_id', sa.String(length=10), nullable=True),
    sa.Column('ie1_type', sa.String(), nullable=True),
    sa.Column('ie2_id', sa.String(length=10), nullable=True),
    sa.Column('ie2_type', sa.String(), nullable=True),
    sa.Column('ie3_id', sa.String(length=10), nullable=True),
    sa.Column('ie3_type', sa.String(), nullable=True),
    sa.Column('ie4_id', sa.String(length=10), nullable=True),
    sa.Column('ie4_type', sa.String(), nullable=True),
    sa.Column('ie5_id', sa.String(length=10), nullable=True),
    sa.Column('ie5_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_timestamp'), 'run', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_timestamp'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
