"""added error table

Revision ID: cc028c2307c3
Revises: 0d6c933d49fa
Create Date: 2021-09-08 15:40:19.308508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc028c2307c3'
down_revision = '0d6c933d49fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=12), nullable=True),
    sa.Column('error_type', sa.String(length=25), nullable=True),
    sa.Column('vii_lot', sa.String(length=20), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('run', 'ie1_type')
    op.drop_column('run', 'ie4_type')
    op.drop_column('run', 'ie3_id')
    op.drop_column('run', 'ie5_type')
    op.drop_column('run', 'ie3_type')
    op.drop_column('run', 'ie2_id')
    op.drop_column('run', 'ie2_type')
    op.drop_column('run', 'ie1_id')
    op.drop_column('run', 'ie4_id')
    op.drop_column('run', 'ie5_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('ie5_id', sa.VARCHAR(length=10), nullable=True))
    op.add_column('run', sa.Column('ie4_id', sa.VARCHAR(length=10), nullable=True))
    op.add_column('run', sa.Column('ie1_id', sa.VARCHAR(length=10), nullable=True))
    op.add_column('run', sa.Column('ie2_type', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('ie2_id', sa.VARCHAR(length=10), nullable=True))
    op.add_column('run', sa.Column('ie3_type', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('ie5_type', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('ie3_id', sa.VARCHAR(length=10), nullable=True))
    op.add_column('run', sa.Column('ie4_type', sa.VARCHAR(), nullable=True))
    op.add_column('run', sa.Column('ie1_type', sa.VARCHAR(), nullable=True))
    op.drop_table('error')
    # ### end Alembic commands ###
